theme: jekyll-theme-minimal
title: M256
description: Industrial Automation Software Development
logo: "https://github.com/M256-Automation/M256-automation.github.io/raw/main/asset/Asset%202request.png"
show_downloads: "false"
